#!/usr/bin/env python

import sys
import os

if __name__ == '__main__':

    if(os.path.islink(__file__)):
        dirPath = os.path.dirname(os.path.abspath(os.readlink(__file__)))
    else:
        dirPath = os.path.dirname(os.path.abspath(__file__))
    print dirPath
    execFile = dirPath + '/src/main.py'
    
    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)

    except OSError, e:
        print >> sys.stderr, 'fork #1 failed: %d (%s)' % (e.errno, e.strerror)
        sys.exit(1)

    os.setsid()
    os.umask(0)

    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)
    except OSError, e:
        print >> sys.stderr, 'fork #2 failed: %d(%s)' (e.errno, e.strerror)
        sys.exit(1)

    os.system('gksu python ' + execFile)
