# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialUI.ui'
#
# Created: Mon Sep  5 22:50:57 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainDialWindow(object):
    def setupUi(self, MainDialWindow):
        MainDialWindow.setObjectName(_fromUtf8("MainDialWindow"))
        MainDialWindow.resize(290, 250)
        MainDialWindow.setMinimumSize(QtCore.QSize(290, 250))
        MainDialWindow.setMaximumSize(QtCore.QSize(290, 250))
        MainDialWindow.setWindowTitle(QtGui.QApplication.translate("MainDialWindow", "802.1x Dialer", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo/image/8021x.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainDialWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(MainDialWindow)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.NICLabel = QtGui.QLabel(MainDialWindow)
        self.NICLabel.setText(QtGui.QApplication.translate("MainDialWindow", "NIC:", None, QtGui.QApplication.UnicodeUTF8))
        self.NICLabel.setObjectName(_fromUtf8("NICLabel"))
        self.gridLayout.addWidget(self.NICLabel, 0, 0, 1, 1)
        self.NICList = QtGui.QComboBox(MainDialWindow)
        self.NICList.setEditable(False)
        self.NICList.setMaxCount(2147483646)
        self.NICList.setObjectName(_fromUtf8("NICList"))
        self.gridLayout.addWidget(self.NICList, 0, 1, 1, 1)
        self.SwitchLabel = QtGui.QLabel(MainDialWindow)
        self.SwitchLabel.setText(QtGui.QApplication.translate("MainDialWindow", "Network:", None, QtGui.QApplication.UnicodeUTF8))
        self.SwitchLabel.setObjectName(_fromUtf8("SwitchLabel"))
        self.gridLayout.addWidget(self.SwitchLabel, 1, 0, 1, 1)
        self.SwitchNetwork = QtGui.QComboBox(MainDialWindow)
        self.SwitchNetwork.setObjectName(_fromUtf8("SwitchNetwork"))
        self.SwitchNetwork.addItem(_fromUtf8(""))
        self.SwitchNetwork.setItemText(0, QtGui.QApplication.translate("MainDialWindow", "Campus Network", None, QtGui.QApplication.UnicodeUTF8))
        self.SwitchNetwork.addItem(_fromUtf8(""))
        self.SwitchNetwork.setItemText(1, QtGui.QApplication.translate("MainDialWindow", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.SwitchNetwork, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.UsernameLabel = QtGui.QLabel(MainDialWindow)
        self.UsernameLabel.setText(QtGui.QApplication.translate("MainDialWindow", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.UsernameLabel.setObjectName(_fromUtf8("UsernameLabel"))
        self.horizontalLayout_2.addWidget(self.UsernameLabel)
        self.UsernameInput = QtGui.QLineEdit(MainDialWindow)
        self.UsernameInput.setObjectName(_fromUtf8("UsernameInput"))
        self.horizontalLayout_2.addWidget(self.UsernameInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.PasswordLabel = QtGui.QLabel(MainDialWindow)
        self.PasswordLabel.setText(QtGui.QApplication.translate("MainDialWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setObjectName(_fromUtf8("PasswordLabel"))
        self.horizontalLayout_3.addWidget(self.PasswordLabel)
        self.PasswordInput = QtGui.QLineEdit(MainDialWindow)
        self.PasswordInput.setEchoMode(QtGui.QLineEdit.Password)
        self.PasswordInput.setObjectName(_fromUtf8("PasswordInput"))
        self.horizontalLayout_3.addWidget(self.PasswordInput)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.IfStorePassword = QtGui.QCheckBox(MainDialWindow)
        self.IfStorePassword.setEnabled(True)
        self.IfStorePassword.setText(QtGui.QApplication.translate("MainDialWindow", "Remeber Password", None, QtGui.QApplication.UnicodeUTF8))
        self.IfStorePassword.setObjectName(_fromUtf8("IfStorePassword"))
        self.horizontalLayout_4.addWidget(self.IfStorePassword)
        self.IfDialStartup = QtGui.QCheckBox(MainDialWindow)
        self.IfDialStartup.setText(QtGui.QApplication.translate("MainDialWindow", "DialAtStart", None, QtGui.QApplication.UnicodeUTF8))
        self.IfDialStartup.setObjectName(_fromUtf8("IfDialStartup"))
        self.horizontalLayout_4.addWidget(self.IfDialStartup)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.LogonButton = QtGui.QPushButton(MainDialWindow)
        self.LogonButton.setText(QtGui.QApplication.translate("MainDialWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.LogonButton.setObjectName(_fromUtf8("LogonButton"))
        self.horizontalLayout_5.addWidget(self.LogonButton)
        self.LogoffButton = QtGui.QPushButton(MainDialWindow)
        self.LogoffButton.setEnabled(False)
        self.LogoffButton.setText(QtGui.QApplication.translate("MainDialWindow", "Logoff", None, QtGui.QApplication.UnicodeUTF8))
        self.LogoffButton.setObjectName(_fromUtf8("LogoffButton"))
        self.horizontalLayout_5.addWidget(self.LogoffButton)
        self.AboutButton = QtGui.QPushButton(MainDialWindow)
        self.AboutButton.setText(QtGui.QApplication.translate("MainDialWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.AboutButton.setObjectName(_fromUtf8("AboutButton"))
        self.horizontalLayout_5.addWidget(self.AboutButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.StatusBar = QtGui.QLabel(MainDialWindow)
        self.StatusBar.setText(QtGui.QApplication.translate("MainDialWindow", "Ready", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusBar.setAlignment(QtCore.Qt.AlignCenter)
        self.StatusBar.setObjectName(_fromUtf8("StatusBar"))
        self.verticalLayout.addWidget(self.StatusBar)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TimeLabel = QtGui.QLabel(MainDialWindow)
        self.TimeLabel.setText(QtGui.QApplication.translate("MainDialWindow", "Online Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.TimeLabel.setObjectName(_fromUtf8("TimeLabel"))
        self.horizontalLayout.addWidget(self.TimeLabel)
        self.TimeDisplay = QtGui.QLabel(MainDialWindow)
        self.TimeDisplay.setText(QtGui.QApplication.translate("MainDialWindow", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeDisplay.setObjectName(_fromUtf8("TimeDisplay"))
        self.horizontalLayout.addWidget(self.TimeDisplay)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(MainDialWindow)
        self.NICList.setCurrentIndex(-1)
        QtCore.QObject.connect(self.LogonButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialWindow.logon)
        QtCore.QObject.connect(self.LogoffButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialWindow.logoff)
        QtCore.QObject.connect(self.AboutButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialWindow.about)
        QtCore.QObject.connect(self.LogonButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialWindow.logOnButtonClicked)
        QtCore.QObject.connect(self.LogoffButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialWindow.logOffButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(MainDialWindow)
        MainDialWindow.setTabOrder(self.NICList, self.UsernameInput)
        MainDialWindow.setTabOrder(self.UsernameInput, self.PasswordInput)
        MainDialWindow.setTabOrder(self.PasswordInput, self.IfStorePassword)
        MainDialWindow.setTabOrder(self.IfStorePassword, self.LogonButton)
        MainDialWindow.setTabOrder(self.LogonButton, self.LogoffButton)

    def retranslateUi(self, MainDialWindow):
        pass

